Only run release workflow from chainguard-dev/actions
Any forks of this repository will have this workflow attempt to run.
It will fail because it does not have credentials to run.

Error looks like this:

    Error: no installation found for "smoser"